### ISSUE TITLE
Add function to rebind going back instead of using strumbar for going back.

### ISSUE THREAD

**Issue by yaladre** [limyz/DTXmaniaNX#115]
Similar to what AL has, just the option to bind a specific button to go back instead of having it always binded to the strumbar.

**Comment by fisyher** [comment]
Cancel button should always be fixed to at least the Esc Key to avoid potential loss of control issue. I will remove the fixed binding of Cancel to the Pick button as it does not make sense. 

As for adding Key configuration function for Enter and Cancel function, I will not implement them unless there is a good reason to do so. Just use Enter and Esc keys for now.

**Comment by fisyher** [comment]
After looking into this deeper, I realized the Pick key is functioning as a built-in Back Command similar to Drum LC which is not the same as the Cancel function in Esc key. 

It is a convenience feature so that player can move out of a directory without the need to scroll all the way to the Back Box and without touching the keyboard. As such, I will not remove this fixed binding for now.

@yaladre: Would you like to elaborate on your issue with using Pick as the Back command?
