### ISSUE TITLE
An option to change the window size of DTXViewerNX, as well as the scroll speed

### ISSUE THREAD

**Issue by Chronon1cal** [limyz/DTXmaniaNX#144]
Currently, I feel that DTXViewerNX is a bit small and crammed when trying to use it. While it is possible to change the size of the window and the scroll speed while it's being used, it reverts back to its original state after closing it. Maybe an option in the DTXCreator options menu for the viewer would be good?

**Comment by fisyher** [comment]
Agreed that the current default size may be quite small, especially for those using 4K resolution monitors. I picked the current size of 640 x 360 because it is the same size used by AL for its DTXViewer. 

The question is what sort of option to put in the Menu? I think that providing a few Size options that maintains 16:9 aspect ratio is better than letting users manually configure Width and Height. @limyz what do you think?

**Comment by limyz** [comment]
User-selectable 16:9/16:10 resolutions is great, they are commonplace in gaming

**Comment by fisyher** [comment]
![image](https://github.com/limyz/DTXmaniaNX/assets/15701545/48ed456b-0dbb-4a6a-a9b8-571345d03120)

These will be the 4 DTXViewerNX Window Size options added to DTXCreator
