### ISSUE TITLE
Bass Progress meter is on wrong side

### ISSUE THREAD

**Issue by yaladre** [limyz/DTXmaniaNX#146]
When using GR Gamemode, the Bass side has it's progress meter on the same side as the Guitar's Progress meter. It should be on the other side, as there is a clear empty gap on the left side of the Bass playfield, and as well GITADORA has the progress meter on the opposite side as well when playing 2-player co-op on a XG cabinet. 
![image](https://user-images.githubusercontent.com/88199650/160250076-7c82077a-b35c-4ea4-8a6f-4452389b69fc.png)

**Comment by fisyher** [comment]
This is not an issue but an intentional decision. If you turn on Result Info and Combo, there will not be any space left on the left side:

![image](https://user-images.githubusercontent.com/15701545/160602453-5ec4e70d-e92a-4f66-a7f5-24ec00998c29.png)

It also does not match the design of the original game to place it on the left. Instead, I am of the opinion that the Excite gauge and Speed display for Bass should be shifted to the right so it looks the same as Guitar. The overall placement should also need to be adjusted accordingly.
